import type { Advice, Language } from './contracts.ts';
import type { decide } from '../../../packages/decision-engine/src/profile.ts';
import { demoProduct } from '../../../packages/decision-engine/src/profile.ts';
import { normalize } from './language.ts';

export function lesson(topic: string, language: Language) {
  const t = normalize(topic);
  const en = language === 'en';
  if (/comision|cost|fee/.test(t)) return en ? 'Fees reduce the money that remains invested. Compare the total annual cost, not only the advertised management fee. A cheaper product still needs to fit your goal and risk.' : 'Las comisiones reducen el dinero que sigue invertido. Compara el coste total anual, no solo la comisión de gestión anunciada. Que un producto sea barato no significa que encaje con tu objetivo y riesgo.';
  if (/inflacion|inflation/.test(t)) return en ? 'Inflation means prices rise and the same money buys less. Investing can help pursue long-term growth, but it carries risk and does not guarantee beating inflation.' : 'La inflación hace que los precios suban y el mismo dinero compre menos. Invertir puede ayudarte a buscar crecimiento a largo plazo, pero tiene riesgo y no garantiza superar la inflación.';
  if (/compuesto|compound/.test(t)) return en ? 'Compounding means returns can themselves generate returns if they remain invested. Costs and losses also accumulate; growth is not guaranteed.' : 'El interés compuesto consiste en que los rendimientos pueden generar nuevos rendimientos si se mantienen invertidos. Las comisiones y las pérdidas también se acumulan; el crecimiento no está garantizado.';
  if (/monetario|money market/.test(t)) return en ? 'A money-market fund holds short-term debt instruments. It can have lower volatility than shares, but it is not a guaranteed deposit and can lose value.' : 'Un fondo monetario invierte en instrumentos de deuda a corto plazo. Puede tener menos volatilidad que las acciones, pero no es un depósito garantizado y puede perder valor.';
  if (/diversific|index|global/.test(t)) return en ? 'Diversifying means spreading your money across different investments instead of depending on one company. A global index fund is one way to do that, but it can still fall in value.' : 'Diversificar es repartir tu dinero entre distintas inversiones para no depender de una sola empresa. Un fondo indexado global es una forma de hacerlo, pero también puede bajar de valor.';
  if (/riesgo|risk|volatil/.test(t)) return en ? 'Volatility is how much an investment moves up and down. Your willingness to tolerate losses is different from what your finances can actually withstand. We use the more cautious limit.' : 'La volatilidad es cuánto sube y baja una inversión. Una cosa es tolerar las pérdidas y otra poder asumirlas sin comprometer tus gastos. Usamos el límite más prudente.';
  return en ? 'Saving keeps money available for near-term needs and emergencies. Investing takes risk in pursuit of longer-term growth. Start by separating the money you need soon from money you can leave invested.' : 'Ahorrar permite tener dinero disponible para necesidades próximas e imprevistos. Invertir supone asumir riesgo buscando crecimiento a largo plazo. Lo primero es separar el dinero que necesitas pronto del que puedes mantener invertido.';
}

export function explain(decision: ReturnType<typeof decide>, language: Language, topic: string): { text: string; advice: Advice } {
  const en = language === 'en';
  const dictionary: Record<string, [string, string, string, string]> = {
    debt: ['Primero atendería tus deudas con intereses altos.', 'Tienen prioridad antes de comprometer más dinero en inversiones.', 'I would address your high-interest debt first.', 'It takes priority before committing more money to investments.'],
    buffer: ['Por ahora reforzaría tu colchón y el margen para tus gastos.', 'Tu información no permite establecer una aportación sostenible con una reserva suficiente.', 'For now, I would strengthen your emergency buffer and room for expenses.', 'Your information does not establish a sustainable contribution with a sufficient reserve.'],
    human: ['Esta demo no conecta con un asesor humano. Puedes contactar con tu entidad por sus canales habituales.', 'No voy a fingir que he solicitado una cita ni transferido esta conversación.', 'This demo cannot connect you with a human adviser. You can contact your bank through its usual channels.', 'No appointment has been made and this conversation has not been transferred.'],
    fomo: ['No concentraría todo tu dinero en una tendencia por miedo a quedarte fuera.', 'Una noticia o una moda no cambia lo que puedes permitirte perder.', 'I would not concentrate all your money in a trend out of fear of missing out.', 'A headline or trend does not change what you can afford to lose.'],
    panic: ['Antes de vender por una caída, revisaría cuándo necesitas el dinero y qué tienes invertido.', 'Una caída por sí sola no permite decidir qué hacer con una cartera que no hemos revisado.', 'Before selling after a fall, I would review when you need the money and what you hold.', 'A fall alone is not enough to decide what to do with a portfolio we have not reviewed.'],
    market_unavailable: ['Ahora mismo no dispongo de noticias ni cotizaciones verificadas en directo.', 'Podemos revisar tu situación, pero no justificar una compra por lo que supuestamente pasa hoy.', 'I do not currently have verified live news or prices.', 'We can review your situation, but cannot justify buying based on supposed events today.'],
    horizon: ['Para ese plazo, no propondría el plan global de esta demo.', 'El producto simulado exige al menos cinco años; necesitar el dinero antes cambia la decisión.', 'For that time horizon, I would not propose the demo global plan.', 'The simulated product requires at least five years; needing the money sooner changes the decision.'],
    risk: ['El riesgo de este plan no encaja con el límite que hemos establecido.', 'Saber más de inversión no aumenta por sí solo tu capacidad para asumir pérdidas.', 'The risk of this plan does not fit the limit we established.', 'Knowing more about investing does not itself increase your capacity to absorb losses.'],
    portfolio_unverified: ['Antes de añadir otra inversión, necesitaría revisar los productos que ya tienes.', 'Una descripción general no permite comprobar concentración, costes ni diversificación.', 'Before adding another investment, I would need to review what you already hold.', 'A general description does not establish concentration, costs or diversification.'],
    amount: ['No propondría una nueva aportación con el margen disponible en esta sesión.', 'La demo descuenta lo que ya has simulado del presupuesto mensual y requiere un mínimo de diez euros.', 'I would not propose another contribution with the budget available in this session.', 'The demo deducts previous simulated contributions from the monthly budget and requires at least ten euros.'],
    compliance: ['No puedo proponer esta inversión con la información disponible.', 'Primero deben resolverse los datos o controles pendientes.', 'I cannot propose this investment with the available information.', 'The outstanding information or checks need to be resolved first.'],
  };
  let text: string;
  let reasons: string[];
  if (decision.action === 'INVEST') {
    const amount = new Intl.NumberFormat(en ? 'en-IE' : 'es-ES', { style: 'currency', currency: 'EUR' }).format(decision.amount!);
    text = en ? `In this simulation, you could try a ${amount} contribution to the global plan.` : `En esta simulación, podrías probar una aportación de ${amount} al plan global.`;
    reasons = en ? ['Your stated time horizon meets the demo product minimum.', 'The amount fits your stated cash flow and emergency reserve.', 'Your risk limit passes the demo rule.'] : ['Tu plazo declarado cumple el mínimo del producto de ejemplo.', 'El importe encaja con el flujo de caja y la reserva que has indicado.', 'Tu límite de riesgo cumple la regla de la demo.'];
  } else if (decision.action === 'LEARN') { text = lesson(topic, language); reasons = []; }
  else { const row = dictionary[decision.reason] ?? dictionary.compliance; text = row[en ? 2 : 0]; reasons = [row[en ? 3 : 1]]; }
  return { text, advice: { action: decision.action, reasons, risk: en ? 'Investments can lose value. This demo does not assess real product suitability or execute trades.' : 'Las inversiones pueden perder valor. Esta demo no evalúa la idoneidad de productos reales ni ejecuta operaciones.', ...(decision.amount !== undefined ? { amount: decision.amount, annualCostPercent: demoProduct.annualCostPercent } : {}), label: decision.action === 'INVEST' ? (en ? 'Review simulation' : 'Revisar simulación') : (en ? 'Continue talking' : 'Seguir hablando') } };
}
