import Head from 'next/head';
import Link from 'next/link';
import { legalDocuments, regulatoryReviews } from '../../legal/documents';

export default function LegalCenter() {
  return <main className="mx-auto max-w-5xl space-y-8 px-5 py-10 text-slate-100">
    <Head><title>Centro legal y regulaciones · KAI</title></Head>
    <Link href="/settings" className="text-sm text-emerald-200">← Ajustes</Link>
    <header><p className="text-xs uppercase tracking-widest text-emerald-200">Transparencia</p><h1 className="mt-3 text-3xl font-semibold">Centro legal y regulaciones</h1><p className="mt-3 text-sm leading-7 text-slate-300">Consulta las condiciones, cómo se tratan tus datos y el estado de revisión por territorio. Última revisión documental: 16 de septiembre de 2026.</p></header>
    <aside className="rounded-2xl border border-amber-300/30 bg-amber-300/10 p-5 text-sm leading-7 text-amber-100">Estamos en fase de demo. No existe una certificación de cumplimiento mundial ni autorización comercial acreditada. Los textos son provisionales: faltan los datos del responsable y la revisión jurídica y operativa de cada mercado. Seleccionar un país en el registro no significa que el servicio esté autorizado allí.</aside>
    <section aria-label="Documentos legales" className="grid gap-4 sm:grid-cols-2">{Object.entries(legalDocuments).map(([key, doc]) => <Link key={key} href={`/legal/${key}`} className="rounded-2xl border border-white/10 bg-slate-900 p-5 hover:border-emerald-300/50"><h2 className="font-semibold">{doc.title} ↗</h2><p className="mt-2 text-xs text-slate-400">Versión {doc.version}</p></Link>)}</section>
    <section><h2 className="text-xl font-semibold">Controles implementados en la demo</h2><ul className="mt-4 list-disc space-y-2 pl-5 text-sm leading-7 text-slate-300"><li>Aceptación explícita de términos y riesgos, lectura de privacidad y declaración de mayoría de edad, verificadas por el servidor.</li><li>Registro de fecha, versiones y país declarado durante la sesión. El registro es temporal, no un archivo probatorio permanente.</li><li>Perfil privado por defecto, protección de solicitudes contra falsificación y operaciones con dinero virtual.</li><li>Sin captura de documentos ni biometría en la verificación simulada.</li></ul></section>
    <section><h2 className="text-xl font-semibold">Revisión normativa por territorio</h2><p className="mt-2 text-sm leading-7 text-slate-400">Inventario inicial, no exhaustivo. Cada país y función requiere determinar las normas aplicables, sus excepciones y las evidencias necesarias.</p><div className="mt-5 grid gap-4 md:grid-cols-2">{regulatoryReviews.map(item => <article key={item.region} className="rounded-2xl border border-white/10 bg-slate-900 p-5"><span className="text-xs text-amber-200">{item.status}</span><h3 className="mt-2 text-lg font-semibold">{item.region}</h3><p className="mt-2 text-sm text-emerald-100">{item.framework}</p><p className="mt-3 text-sm leading-7 text-slate-300">{item.detail}</p>{item.url && <a href={item.url} target="_blank" rel="noopener noreferrer" className="mt-4 inline-block text-xs text-emerald-200 underline">Fuente oficial de referencia ↗</a>}</article>)}</div></section>
    <section className="rounded-2xl border border-white/10 p-5"><h2 className="text-xl font-semibold">Antes de cada nueva función</h2><p className="mt-3 text-sm leading-7 text-slate-300">El proceso de desarrollo debe revisar países de destino, datos utilizados, menores, accesibilidad, seguridad, moderación y posibles licencias; actualizar los textos y verificar los controles. Las nuevas actividades reguladas requieren una revisión específica antes de ofrecerse. Este proceso no equivale a una aprobación jurídica automática.</p></section>
  </main>;
}
